{
 "title": "RabbitMQ",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  for 4371 Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(rabbitmq_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Stats",
   "type": "graph",
   "description": "rabbitmq节点状态",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "rabbitmq内存使用信息",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "description": "RabbitMQ 管理的网络套接字数量和限制。\n当限额用尽时，RabbitMQ 将停止接受新的网络连接",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "description": "文件描述符",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{instance=~\"$instance.*\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "description": "使用中的交换机总数",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_exchangesTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:exchanges"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "description": "打开的channel总数",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_channelsTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:channels"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "description": "信息消费者总数",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_consumersTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:consumers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "打开的连接总数",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:connections"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "description": "正在使用的队列总数",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queuesTotal{instance=~\"$instance.*\"}",
     "legendFormat": "{{instance}}:queues"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "graph",
   "description": "已处理和未处理报文的总和（队列深度）",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{instance=~\"$instance.*\"} > 0",
     "legendFormat": "{{queue}}:{{durable}}"
    }
   ]
  },
  {
   "title": "Queue / UnAck",
   "type": "graph",
   "description": "未确认的队列消息大小",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_message_bytes_unacknowledged{instance=~\"$instance.*\"} > 0",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages / Host",
   "type": "graph",
   "description": "ready: 准备发送给客户的信息数量\n\npublished: 已发布信息的计数\n\ndelivered: 以确认模式发送给用户的报文计数\n\nunack: 发送给客户但尚未确认的信息数量",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged{instance=~\"$instance.*\"})",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  }
 ]
}