{
 "title": "ElasticSearch",
 "description": "ElasticSearch cluster stats.Revision 1 of this dashboard is the same as the Infinity Dashboard Revision 4 (https://grafana.com/dashboards/2322)This is a cleaned up copy with all control characters removed from the dashboard file.  When downloading version 4 of the original Infinity elasticsearch dashboard via curl, the resulting file is corrupted with a missing final curly brace.[6483]",
 "tags": [
  "elasticsearch",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(elasticsearch_indices_docs{job=~\".*elasticsearch_exporter\"},job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_indices_docs{job=\"$job\"},cluster)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{job=\"$job\",cluster=\"$cluster\", name!=\"\"},instance)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(elasticsearch_indices_docs{job=\"$job\",cluster=\"$cluster\",instance=~\"$instance\",name!=\"\"},host)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{job=\"$job\",cluster=\"$cluster\", instance=\"$instance\",name!=\"\",host=\"$host\"},name)"
   },
   { "name": "interval", "label": "Interval", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"yellow\"}==1)+2"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}>0)"
    }
   ]
  },
  {
   "title": "useCPU ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} ) / count (elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} )"
    }
   ]
  },
  {
   "title": "JVM UseMemory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "singlestat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "singlestat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  { "title": "Translog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total translog operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_size_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Tripped for breakers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_tripped{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{breaker}}"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_estimated_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{breaker}}"
    },
    {
     "expr": "elasticsearch_breakers_limit_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: limit for {{breaker}}"
    }
   ]
  },
  { "title": "CPU, Memory, Disk, Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk Usage %" }
   ],
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: sent "
    },
    {
     "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Documents count on node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "graph",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Total Operations  rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_tota{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_rejected_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Field data memory size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 80 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Evictions from filter cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_filter_cache_evictions{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Count of index segments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current memory size of segments in bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }
  },
  {
   "title": "Count of documents with only primary shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with only primary shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with all shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Index writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Index writer with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Index writer with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Segments with only primary shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_count_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Segments with all shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_count_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of segments with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of segments with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Doc values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Doc values with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Doc values with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Fields", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "Size of fields with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of fields with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Fixed bit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Size of fixed bit with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of fixed bit with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Norms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Size of norms with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of norms with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Size of points with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of points with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Terms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Size of terms with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_terms_memory_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Number of terms with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_terms_memory_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Version map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "Size of version map with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_version_map_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of version map with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_version_map_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}