{
 "title": "Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x (763)",
 "tags": [ "redis" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(redis_up{job=~\".*redis_exporter\"}, job)"
   },
   {
    "name": "instance",
    "query": "label_values(redis_up{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "redis_instance_info" }
   ]
  },
  {
   "title": "Memory Percent of Usage",
   "type": "singlestat",
   "description": "内存使用百分比\nN/A表示不限制内存使用",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (avg(redis_memory_used_bytes{instance=~\"$instance\"}) / avg(redis_memory_max_bytes{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "slave",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "ConfigMaxMemory ",
   "type": "stat",
   "description": "配置的最大内存",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_config_maxmemory{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "mem_fragmentation_ratio",
   "type": "stat",
   "description": "内存碎片率（>1.5 说明碎片严重）",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HistoryMaxUsageMemory ",
   "type": "stat",
   "description": "Redis 历史上使用的最大内存",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_peak_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RedisStartupMemory ",
   "type": "stat",
   "description": "Redis 启动时使用的内存",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_startup_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "ResidentMemory ",
   "type": "stat",
   "description": "常驻内存大小",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "TotalUsageMemory ",
   "type": "stat",
   "description": "目前使用的内存",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RedisUsageMemory ",
   "type": "stat",
   "description": "Redis 内部数据结构和管理开销占用的内存",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_overhead_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "TotalUsagePhysicalMemory ",
   "type": "stat",
   "description": "Redis 实际从操作系统分配的物理内存",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_rss_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "MaxAvailableMemory ",
   "type": "stat",
   "description": "设置的最大内存",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "DatasetUsageMemory ",
   "type": "stat",
   "description": "存储数据的内存",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_dataset_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CacheShellMemory ",
   "type": "stat",
   "description": "已缓存的脚本内存",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_scripts_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "LuaUsageMemory ",
   "type": "stat",
   "description": "Lua 脚本使用的内存",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_lua_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(redis_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$node_memory\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}",
     "legendFormat": "{{app}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  }
 ]
}